name = "QGL"
uuid = "ad0c24d0-9e87-4ecb-bb43-4b3bae5867a1"
authors = ["Colm Ryan", "Blake Johnson"]
licence = "Apache"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
